# Generated by Django 6.0.4 on 2026-04-30 20:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Paiement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10)),
                ('methode', models.CharField(choices=[('especes', 'Especes'), ('mobile_money', 'Mobile Money'), ('carte', 'Carte bancaire')], default='especes', max_length=30)),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('paye', 'Paye'), ('echoue', 'Echoue'), ('rembourse', 'Rembourse')], default='en_attente', max_length=20)),
                ('reference', models.CharField(blank=True, max_length=100, unique=True)),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('paye_le', models.DateTimeField(blank=True, null=True)),
                ('reservation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='paiement', to='booking.reservation')),
            ],
            options={
                'db_table': 'paiement',
                'ordering': ['-cree_le'],
            },
        ),
    ]
