# Generated by Django 6.0.4 on 2026-04-30 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paiement',
            name='reference',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
