# Generated by Django 6.0.4 on 2026-04-30 20:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('transport', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('confirmee', 'Confirmee'), ('annulee', 'Annulee'), ('terminee', 'Terminee')], default='en_attente', max_length=20)),
                ('nb_passagers', models.PositiveIntegerField(default=1)),
                ('prix_estime', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('date_trajet', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('mis_a_jour_le', models.DateTimeField(auto_now=True)),
                ('arrivee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservations_arrivee', to='transport.arret')),
                ('depart', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservations_depart', to='transport.arret')),
                ('trajet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservations', to='transport.trajethistorique')),
                ('utilisateur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reservations_taxi', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'reservation',
                'ordering': ['-cree_le'],
            },
        ),
    ]
