# Generated by Django 6.0.4 on 2026-04-30 20:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfilUtilisateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telephone', models.CharField(blank=True, max_length=30)),
                ('role', models.CharField(choices=[('client', 'Client'), ('chauffeur', 'Chauffeur'), ('admin', 'Administrateur')], default='client', max_length=20)),
                ('adresse', models.CharField(blank=True, max_length=255)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profil_taxi', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'profil_utilisateur',
                'ordering': ['user__username'],
            },
        ),
    ]
