# Generated by Django 6.0.4 on 2026-04-30 20:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Arret',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=120, unique=True)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
            ],
            options={
                'verbose_name': 'arret',
                'verbose_name_plural': 'arrets',
                'db_table': 'arret',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='Ligne',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=20, unique=True)),
                ('nom', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'ligne',
                'ordering': ['numero', 'nom'],
            },
        ),
        migrations.CreateModel(
            name='Correspondance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temps_estime_minutes', models.PositiveIntegerField(default=5)),
                ('arret', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='correspondances', to='transport.arret')),
                ('ligne_arrivee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='correspondances_arrivee', to='transport.ligne')),
                ('ligne_depart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='correspondances_depart', to='transport.ligne')),
            ],
            options={
                'db_table': 'correspondance',
                'ordering': ['arret__nom', 'ligne_depart__numero', 'ligne_arrivee__numero'],
            },
        ),
        migrations.CreateModel(
            name='LigneArret',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordre', models.PositiveIntegerField()),
                ('arret', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transport.arret')),
                ('ligne', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transport.ligne')),
            ],
            options={
                'db_table': 'ligne_arret',
                'ordering': ['ligne__numero', 'ordre'],
            },
        ),
        migrations.AddField(
            model_name='ligne',
            name='arrets',
            field=models.ManyToManyField(related_name='lignes', through='transport.LigneArret', to='transport.arret'),
        ),
        migrations.CreateModel(
            name='TrajetHistorique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nb_changements', models.PositiveIntegerField(default=0)),
                ('duree_minutes', models.PositiveIntegerField(default=0)),
                ('distance_km', models.FloatField(default=0)),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('arrivee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='trajets_arrivee', to='transport.arret')),
                ('correspondances', models.ManyToManyField(blank=True, related_name='trajets', to='transport.correspondance')),
                ('depart', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='trajets_depart', to='transport.arret')),
                ('lignes', models.ManyToManyField(blank=True, related_name='trajets', to='transport.ligne')),
            ],
            options={
                'db_table': 'trajet_historique',
                'ordering': ['-cree_le'],
            },
        ),
        migrations.AddConstraint(
            model_name='correspondance',
            constraint=models.UniqueConstraint(fields=('arret', 'ligne_depart', 'ligne_arrivee'), name='unique_correspondance'),
        ),
        migrations.AddConstraint(
            model_name='lignearret',
            constraint=models.UniqueConstraint(fields=('ligne', 'arret'), name='unique_ligne_arret'),
        ),
        migrations.AddConstraint(
            model_name='lignearret',
            constraint=models.UniqueConstraint(fields=('ligne', 'ordre'), name='unique_ordre_par_ligne'),
        ),
    ]
